//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 04:13:10 PM EDT 
//


package com.github.spyhunter99.werp.sunjaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         An endpoint definition has several attributes:
 *            "name" - the endpoint name
 *            "implementation" - the name of the endpoint implementation class
 *            "wsdl" - the name of a resource corresponding to the WSDL document for the endpoint
 *            "service" - the QName of the WSDL service that owns this endpoint;
 *            "port" - the QName of the WSDL port for this endpoint;
 *            "url-pattern" - the URL pattern this endpoint is mapped to.
 *            "binding" - specify binding id for SOAP1.1 or SOAP1.2
 *            "enable-mtom" - Enables MTOM optimization
 *         "wsdl", "service", "port" attributes are required for provider based endpoints
 *       
 * 
 * <p>Java class for endpointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="endpointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="handler-chain" type="{http://java.sun.com/xml/ns/jax-ws/ri/runtime}handler-chainType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="implementation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wsdl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="service" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="url-pattern" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="binding" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enable-mtom" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "endpointType", propOrder = {
    "handlerChain"
})
public class EndpointType {

    @XmlElement(name = "handler-chain")
    protected HandlerChainType handlerChain;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "implementation", required = true)
    protected String implementation;
    @XmlAttribute(name = "wsdl")
    @XmlSchemaType(name = "anyURI")
    protected String wsdl;
    @XmlAttribute(name = "service")
    @XmlSchemaType(name = "anyURI")
    protected String service;
    @XmlAttribute(name = "port")
    @XmlSchemaType(name = "anyURI")
    protected String port;
    @XmlAttribute(name = "url-pattern", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String urlPattern;
    @XmlAttribute(name = "binding")
    protected String binding;
    @XmlAttribute(name = "enable-mtom")
    protected Boolean enableMtom;

    /**
     * Gets the value of the handlerChain property.
     * 
     * @return
     *     possible object is
     *     {@link HandlerChainType }
     *     
     */
    public HandlerChainType getHandlerChain() {
        return handlerChain;
    }

    /**
     * Sets the value of the handlerChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlerChainType }
     *     
     */
    public void setHandlerChain(HandlerChainType value) {
        this.handlerChain = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplementation(String value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the wsdl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdl() {
        return wsdl;
    }

    /**
     * Sets the value of the wsdl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdl(String value) {
        this.wsdl = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the urlPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlPattern() {
        return urlPattern;
    }

    /**
     * Sets the value of the urlPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlPattern(String value) {
        this.urlPattern = value;
    }

    /**
     * Gets the value of the binding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinding() {
        return binding;
    }

    /**
     * Sets the value of the binding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinding(String value) {
        this.binding = value;
    }

    /**
     * Gets the value of the enableMtom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableMtom() {
        return enableMtom;
    }

    /**
     * Sets the value of the enableMtom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableMtom(Boolean value) {
        this.enableMtom = value;
    }

}
